name: Test example.py

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - uses: actions/cache@v3
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-
    - name: Install dependencies
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        test -f requirements.txt && pip install -r requirements.txt
    - name: Run example.py
      run: ./example.py
    - name: Assert outputs exist
      run: |
        cd example_images/turtles
        test -f result_group.png
        test -f result_augment.png
